insert into train (id, train_name, train_number)
values(1,'Shinkansen','1'),
      (2,'TGV','2'),
      (3,'Eurostar','3'),
      (4,'Trans-Siberian Railway','4'),
      (5,'Orient Express','5'),
      (6,'Acela Express','6'),
      (7,'Maglev','7'),
      (8,'Freight train','8'),
      (9,'Amtrak Cascades','9'),
      (10,'Indian Pacific','10'),
      (11,'The Blue Train','11'),
      (12,'The Glacier Express','12'),
      (13,'The Bernina Express','13'),
      (14,'The Royal Scotsman','14');