insert into train ( train_name, train_number)
values('Shinkansen','1'),
      ('TGV','2'),
      ('Eurostar','3'),
      ('Trans-Siberian Railway','4'),
      ('Orient Express','5'),
      ('Acela Express','6'),
      ('Maglev','7'),
      ('Freight train','8'),
      ('Amtrak Cascades','9'),
      ('Indian Pacific','10'),
      ('The Blue Train','11'),
      ('The Glacier Express','12'),
      ('The Bernina Express','13'),
      ('The Royal Scotsman','14');